import java.io.FileWriter;
import java.io.IOException;
import java.io.File;
import java.nio.file.Paths;

import java.io.PrintStream;
import java.util.List;
import java.util.logging.Logger;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }

    public String bestCharge(List<String> inputs) {
        //TODO: write code here
        StringBuilder str = new StringBuilder();
        double sum =0;
        double save = 0;
        int check = 0;
        str.append("============= Order details =============\n");
        for(int i =0 ; i< inputs.size();i++){
            String[] item;
            item = inputs.get(i).split(" ");

            for(int j=0;j<itemRepository.findAll().size();j++){
                if(itemRepository.findAll().get(j).getId().compareTo(item[0])==0 ){

                    str.append(itemRepository.findAll().get(j).getName() + " x " + item[2] + " = " + (int)itemRepository.findAll().get(j).getPrice()*(Integer.parseInt(item[2]))+ " yuan\n");
                    sum = sum + itemRepository.findAll().get(j).getPrice()*(Integer.parseInt(item[2]));
                    if(salesPromotionRepository.findAll().get(1).getRelatedItems().contains(item[0])){
                        save  = save + itemRepository.findAll().get(j).getPrice()*(Integer.parseInt(item[2]))/2;
                    }
                    break;
                }
            }

        }
            if(sum>30 || save != 0)
            {
                str.append("-----------------------------------\nPromotion used:\n");
                double hard = sum -6;
                if(sum-save< hard){
                    str.append(salesPromotionRepository.findAll().get(1).getDisplayName() + " (Braised chicken，Cold noodles)，saving "+(int)save+ " yuan\n" );
                    check=1;

                }
                else {str.append("满30减6 yuan，saving 6 yuan\n");
                        check=2;}

            }


        str.append("-----------------------------------\n");
        if(check ==1)
            str.append("Total："+ (int)(sum-save) + " yuan\n");
        else if (check ==2)   str.append("Total："+ (int)(sum-6) + " yuan\n");
        else str.append("Total："+ (int)(sum) + " yuan\n");
        str.append("===================================");

return str.toString();
    }
}