import java.util.Arrays;
import java.util.List;

import static java.lang.Integer.valueOf;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private ItemRepository itemRepository;
    private SalesPromotionRepository salesPromotionRepository;

    public App(ItemRepository itemRepository, SalesPromotionRepository salesPromotionRepository) {
        this.itemRepository = itemRepository;
        this.salesPromotionRepository = salesPromotionRepository;
    }
    

    public void bestCharge(List<String> inputs) {
        //TODO: write code here
        int sum =0;
        int save = 0;
        System.out.println("============= Order details =============");
        for(int i =0 ; i< inputs.size();i++){
            String name;

            String[] item = new String[5];
            item = inputs.get(i).split(" ");
            if(ALL_SALES_PROMOTIONS.get(1).getRelatedItems().contains(item[0])){
                save += ALL_ITEMS.get(i).getPrice()/2;

            }
                if (ALL_ITEMS.get(i).getId().compareTo(item[0]) == 0) {
                    System.out.println(ALL_ITEMS.get(i).getName() + " x "+ item[2] + "  =" + (ALL_ITEMS.get(i).getPrice()*valueOf(item[2]) ));
                    sum+=(ALL_ITEMS.get(i).getPrice()*valueOf(item[2]));
                }
        }
        int check = 0;

        for (int i=0;i<ALL_SALES_PROMOTIONS.size();i++){

            if(sum>30 || save != 0){
                System.out.println("-----------------------------------");
                System.out.println("Promotion used:");
                int price1=sum-6;
                if((sum-save < price1 )){
                    check=1;
                    System.out.println(ALL_SALES_PROMOTIONS.get(1).getDisplayName()+ " saving "+ (sum-save)+"yuan");
                }
                else { check =2;
                    System.out.println(ALL_SALES_PROMOTIONS.get(0).getDisplayName()+ " saving "+ price1 + "yuan");}
            }

        }

        System.out.println("-----------------------------------");
        if(check ==1)
        System.out.println("Total:" + (sum-save)+ " yuan" );
        else if(check==2)
            System.out.println("Total:" + (sum-6)+ " yuan" );
        else System.out.println("Total:" +sum+ " yuan" );
        System.out.println("===================================");

    }
}
